# Generated by Django 6.1.1 on 2026-09-26 21:15

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0144_customfield_status'),
        ('netbox_uc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyaddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='sip_trunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='netbox_uc.siptrunk'),
        ),
        migrations.CreateModel(
            name='SIPTrunkEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('fqdn_or_ip', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=5060, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('protocol', models.CharField(blank=True, max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sip_trunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='netbox_uc.siptrunk')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'SIP trunk endpoint',
                'verbose_name_plural': 'SIP trunk endpoints',
                'ordering': ('sip_trunk', 'priority', 'fqdn_or_ip'),
                'unique_together': {('sip_trunk', 'fqdn_or_ip', 'port')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
